server:
  port: 19999

spring:
  application:
    name: demo-provider
  cloud:
    nacos:
      server-addr: localhost:18848,localhost:28848,localhost:38848
      discovery:
        server-addr: ${spring.cloud.nacos.server-addr}

