server:
  port: 21102

spring:
  application:
    name: demo-provider

  cloud:
    #Sentinel配置项，对应SentinelProperties 配置属性类
    sentinel:
      enabled: true  #是否开启，默认为true
      eager: true  #是否饥饿加载，默认为false。
      transport:
        dashboard: 127.0.0.1:7070 #Sentinel控制台地址
      filter:
        url-patterns: /** #拦截请求的地址，默认为 /* (只是一级目录)

      #Sentinel规则数据源是一个Map类型。key为数据源的名称，可自定义，value为数据源的配置
      datasource:
        ds1:
          #对应DataSourcePropertiesConfiguration 类
          nacos:
            serverAddr: 127.0.0.1:18848
            namespace: #命名空间
            groupId: demo-provider #Nacos分组
            dataType: json #规则数据格式
            ruleType: FLOW #规则类型  详见 RuleType
            dataId: ${spring.application.name}-${spring.cloud.sentinel.datasource.ds1.nacos.ruleType} # Nacos 配置集编号



