server:
  port: 8081


spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/cc?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 111111
  mail:
    host: smtp.163.com
    password:
    port: 465
    properties:
      mail:
        imap:
          ssl:
            socketFactory:
              fallback: false
        smtp:
          auth: true
          ssl:
            enable: true
            socketFactory:
              class: javax.net.ssl.SSLSocketFactory
          starttls:
            enable: false
            required: false
    test-connection: false
    username: ck_chenwang@163.com


mybatis-plus:
  mapper-locations: classpath:mapper/*/*.xml
  type-aliases-package: com.cc.spring.entity
  configuration:
    map-underscore-to-camel-case: true

a: ${random.uuid}
