#Rocketmq配置 ，对应RocketMQProperties 类
rocketmq:
  name-server: localhost:9876 # RocketMQ Namesrv,如果多个，使用逗号分隔。
  # Producer 配置项
  producer:
    group: demo-producer-group #生产者分组
    send-message-timeout: 3000 #发送消息超时时间
    compress-message-body-threshold: 4096 #消息压缩阈值，当消息大小超过该值，就进行消息压缩。默认是4*1024B
    max-message-size: 4194304 #消息体最大值，默认为4KB
    retry-times-when-send-failed: 2 #同步发送消息，失败重试次数，默认是2次
    retry-times-when-send-async-failed: 2 #异步发送消息，失败重试次数，默认2次
    retry-next-server: false #发送消息给Broker时，如果发送失败，是否重试另一台Broker。默认false
    access-key: #Access Key ,可阅读 https://github.com/apache/rocketmq/blob/master/docs/cn/acl/user_guide.md
    secret-key: #Secret Key
    enable-msg-trace: true #是否开启消息轨迹功能，默认开启。可阅读 https://github.com/apache/rocketmq/blob/master/docs/cn/msg_trace/user_guide.md 文档
    customized-trace-topic: RMQ_SYS_TRACE_TOPIC #自定义消息轨迹的topic。默认RMQ_SYS_TRACE_TOPIC
  #Consumer 配置项
  consumer:
    listeners: # 配置某个消费分组，是否监听指定topic。结构为 Map<String, Map<String, Boolean>> （Map<消费者分组, <Topic, Boolean>>） 。默认情况下，不配置表示监听
      test-consumer-group:
        topic1: false

