server:
  port: 21001

spring:
  application:
    name: demo-consumer
  cloud:
    nacos:
      server-addr: localhost:18848,localhost:28848,localhost:38848
      discovery:
        server-addr: ${spring.cloud.nacos.server-addr}

#开启feign对hystrix的支持
feign:
  hystrix:
    enabled: true
