management:
  endpoints:
    web:
      exposure:
        include: '*' #需要开放的端点。默认只打开 health 和info 两个端点。通过设置 * 可以开放所有端点
  endpoint:
    # Health端点配置项，对应HealthProperties配置类
    health:
      enabled: true  #是否开启，默认开启
      show-details: always #何时显示完整的健康信息。默认为 NEVER 都不展示。可选 WHEN_AUTHORIZED 当经过授权的用户；可选 ALWAYS 总是展示。
