server:
  port: 21000

management:
  endpoints:
    web:
      exposure:
        include: 'hystrix.stream' # 需要开放的端点。默认值只打开 health 和 info 两个端点。通过设置 * ，可以开放所有端点。


spring:
  application:
    name: demo-consumer
  cloud:
    nacos:
      server-addr: localhost:18848,localhost:28848,localhost:38848
      discovery:
        server-addr:




